pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = '486991249421.dkr.ecr.ap-south-1.amazonaws.com/wisecow-app'
        CLUSTER_NAME = 'wisecow-cluster'
        SERVICE_NAME = 'wisecow-service'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                // í ½í´¥ Force Jenkins to use 'main' branch instead of default 'master'
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/sumitgaikwad08/wisecow.git'
            }
        }

        stage('Docker Build & Push to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
                docker build -t $ECR_REPO:$IMAGE_TAG .
                docker push $ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to ECS') {
            steps {
                sh '''
                aws ecs update-service \
                  --cluster $CLUSTER_NAME \
                  --service $SERVICE_NAME \
                  --force-new-deployment \
                  --region $AWS_REGION
                '''
            }
        }
    }
}

